#!/usr/bin/env sh

export WLR_RENDERER=vulkan

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

export WLR_DRM_NO_MODIFIERS=1
export WLR_NO_HARDWARE_CURSORS=1

dbus-run-session /usr/sbin/sway
