#!/usr/bin/env sh

kernel_version="$(uname -r)"
module_path="/lib/modules/$kernel_version"

[ -d "$module_path" ] ||
    (notify-send -u 'normal' \
        "Kernel Upgraded to Version $kernel_version" \
        "Modules now reside in $module_path.\n\nReboot to use the new kernel.";
    echo '(reboot now)')
