#!/usr/bin/env bash

set -eou pipefail
set -x

sys=''
val=''
wobsock="$XDG_RUNTIME_DIR/wob.sock"
sink="@DEFAULT_AUDIO_SINK@"

set_volume() {
	wpctl set-volume -l 1.5 "$sink" "$val"
	local cur_vol
	cur_vol="$(wpctl get-volume "$sink" |
		cut -c 9-12 |
		xargs -I '{}' echo 'scale=4;{}*100' |
		bc |
		cut -d "." -f 1)"
	echo "$cur_vol"
	echo "$cur_vol" >"$wobsock"
}

set_brightness() {
	local cur_bright
	cur_bright="$(brightnessctl set "$val" | sed -En 's/.*\(([0-9]+)%\).*/\1/p')"
	echo "$cur_bright" >"$wobsock"
	exit 0
}

while getopts "vbs:i:d:" opt; do
	case "${opt}" in
	v)
		[ -n "$sys" ] && exit 1 || sys="volume"
		;;
	b)
		[ -n "$sys" ] && exit 1 || sys="brightness"
		;;
	s)
		wobsock="${OPTARG}"
		;;
	i)
		[ -n "$val" ] && exit 1 || val="${OPTARG}%+"
		;;
	d)
		[ -n "$val" ] && exit 1 || val="${OPTARG}%-"
		;;
	*)
		exit 1
		;;
	esac
done

if [[ "$sys" == "volume" ]]; then
	set_volume
elif [[ "$sys" == "brightness" ]]; then
	set_brightness
fi
