icons_format = "{icon}"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
format = " $icon $utilization.eng(w:3) "  
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "temperature"
format = " $icon $average.eng(w:3) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used.eng(w:2) "

[[block]]
block = "sound"  
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
empty_format = " $icon $percentage "
not_charging_format = " $icon $percentage "

[[block]]
block = "net"
format = " $icon {$ssid|$ip}($device) "
format_alt = " $icon D:$speed_down.eng(w:3) U:$speed_up.eng(w:3) "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m/%Y %T') "
