preload=/home/ross/Pictures/wallpapers/Gurren Lagann/simon.jpg
preload=/home/ross/Pictures/wallpapers/Evangelion/landscape.jpg

wallpaper=DP-1,/home/ross/Pictures/wallpapers/Gurren Lagann/simon.jpg
wallpaper=HDMI-A-1,/home/ross/Pictures/wallpapers/Evangelion/landscape.jpg
